### ISSUE TITLE
[DatabaseApp] Именование

### ISSUE THREAD

**Issue by pavel-b-novikov** [GlushakovPogodin/nsudotnet#1]
Я уже говорил что за такое "соблюдение" гайдлайнов буду с порога давать в руки решарпер и отправлять

**Comment by GlushakovPogodin** [comment]
Да, у нас возникали сомнения по этому поводу. Это всё-таки аббревиатуры... По-моему, на одной из первых лекций поднимался этот вопрос, но я не помню, чем всё кончилось. Исправить можем без проблем.

**Comment by pavel-b-novikov** [comment]
Нет, я говорю о том, что RootNamespace у вас неправильный. Посмотрите хоть как у других.

**Comment by GlushakovPogodin** [comment]
Вы имеете в виду Data, Logic, UI? Исправим.

**Comment by pavel-b-novikov** [comment]
Молодцы какие.

**Comment by GlushakovPogodin** [comment]
Исправлено :)
