### ISSUE TITLE
[DatabaseApp] Строка подключения в ресурсах?

### ISSUE THREAD

**Issue by pavel-b-novikov** [GlushakovPogodin/nsudotnet#2]
Кто вас научил этому гениальному ходу? Я уже второй раз встречаю и с удивлением замечаю, что там где все нормальные люди хранят строки подключения в app.config, чтобы их можно было поменять не пересобирая приложение, вы почему-то кладете в ресурсы.
Что это было?

**Comment by pavel-b-novikov** [comment]
К тому же еще и не в Applications settings, где даже специальный тип записи есть для хранения референсов и строк подключений, а вот так вот, вероломно, в ресурсах.

К тому же эти ресурсы спрятаны в properties. Зачем в Properties? Чтобы преподаватель не увидел?

И еще и дублируются во всех трех проектах. Чтобы окончательно выбесить преподавателя, который пытается ваше приложение запустить?

**Comment by GlushakovPogodin** [comment]
Блин, да на самом деле просто не имели понятия (и опыта в этом плане) обо всей этой системе. Первое, что пришло в голову, - засунуть в ресы. А первое место, где нашли эти ресурсы, - properties. Будем знать. Исправим.
