### ISSUE TITLE
[DatabaseApp] CrudBase

### ISSUE THREAD

**Issue by pavel-b-novikov** [GlushakovPogodin/nsudotnet#3]
Ребята, или вы мне рассказываете почему все сервисы сделаны копипастом вместо общего Generic-интерфейса для вытягивания сущностей (у вас даже пример был перед глазами - sic!), или берете и впиливаете его, убирая весь тщательно копипащенный код

**Comment by GlushakovPogodin** [comment]
Да-да. Есть такое дело. У нас единственное оправдание. Когда начинали делать, полагали, что сервисы будут достаточно отличаться. Когда сделали, решили оставить так. Из-за лени и нехватки времени. Если необходимо - исправим без проблем.

**Comment by pavel-b-novikov** [comment]
Ладно. Забейте. У вас есть задача важнее.
