### ISSUE TITLE
[DatabaseApp] IncludeProjection

### ISSUE THREAD

**Issue by pavel-b-novikov** [GlushakovPogodin/nsudotnet#4]
Вы использовали мой инклюд для реализации задачи.
Но сейчас я вижу, что он де-факто не используется, потому что включена ленивая загрузка с которой инклюд не нужен.

Теперь собсно объясните мне для чего я его все-таки написал?

**Comment by GlushakovPogodin** [comment]
Вот щас поподробней. Или я чего-то не понимаю? Он же вроде наоборот нужен при ленивой загрузке? Чтобы не строить цепочки инклюдов?
Ну а инклюды, как я понимаю, нужны, чтобы корректно вытаскивать информацию из связанных сущностей. Чтобы как раз из-за этой ленивой загрузки у нас null'ы не повыскакивали.

**Comment by pavel-b-novikov** [comment]
А вот и нет. Он нужен для eager loading. Думаем дальше.

**Comment by GlushakovPogodin** [comment]
Да, значит, мы напутали. Именно при жадной загрузке для того, чтобы загрузилась одна entity, нужно загрузить сначала связанные с ней. Их мы и должны указывать с помощью инклюдов. А Ваш метод автоматизирует эту задачу.
При ленивой же загрузке все связанные сущности загружаются автоматически при первом обращении к связанным сущностям.

**Comment by pavel-b-novikov** [comment]
Именно так. А чем меня не устроил lazy-подход? Он в общем и целом оправдывает себя для множества мелких методов апдейта/выборки.

**Comment by GlushakovPogodin** [comment]
Как я понимаю, если у нас много связнанных сущностей, то при ленивой загрузке происходит новое обращение к базе данных для подгрузки каждой связанной сущности. А при жадной загрузке  все связанные сущности загружаются в одно обращение.

**Comment by pavel-b-novikov** [comment]
Да вы прям капитан очевидность.
Напишите Воронову - он вам объяснит почему я отключаю ленивую загрузку.

**Comment by GlushakovPogodin** [comment]
Нельзя открыть более одного DataReader'а на соединение. А в случае вызовов связанных сущностей могут возникнуть коллизии с его открытием (один DataReader не прекратил работу, а другой пытается создаться).

**Comment by pavel-b-novikov** [comment]
Молодец, объяснил.
