### ISSUE TITLE
[DatabaseApp] Декомпозиция

### ISSUE THREAD

**Issue by pavel-b-novikov** [GlushakovPogodin/nsudotnet#5]
ОО-декомпозиция как всегда хромает. Мда.
Вот сейчас вы берете какое-нибудь одно окно из вашего замечательного приложения и форму редактирования реализуете отдельным контролом и отдельной вью-моделью с валидацией через IDataErrorInfo, потому что словами, чтобы вы прониклись прям, я не могу объяснить в чем ваше заблуждение.

**Comment by GlushakovPogodin** [comment]
Вызов принят. Будем делать.

**Comment by GlushakovPogodin** [comment]
Всё, добавили новую версию проекта.

**Comment by pavel-b-novikov** [comment]
Ну и в каком из 3х ресурсных файлов на этот раз строка подключения?

**Comment by GlushakovPogodin** [comment]
Как и у всех, находится в конфиге UI.
А где должна находиться?

**Comment by pavel-b-novikov** [comment]
да блин. вы почему не удалили неиспользуемые ресурсы тогда?

**Comment by GlushakovPogodin** [comment]
Ясно, удалим.

**Comment by GlushakovPogodin** [comment]
Удалено.
